import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { approveProfile, buildProfile, buildProjection, reviewProfile, sha256 } from '../scripts/lib/bi-discovery-s2/core.mjs';
import { dolibarr2203, deriveDolibarrKnowledge, dolibarrProjectionSpec } from '../scripts/lib/bi-discovery-s2/dolibarr-fixture.mjs';
import { normalizeMariaDbProfile, planMariaDbProfile } from '../scripts/lib/bi-discovery-s2/mariadb-adapter.mjs';
import { createSupersetBundle } from '../scripts/lib/bi-discovery-s2/superset-consumer.mjs';

const load=async()=>JSON.parse(await readFile(new URL('./fixtures/bi-discovery-s2/dolibarr-mariadb-profile-v1.json',import.meta.url),'utf8'));
const approve=async()=>{ const normalized=normalizeMariaDbProfile(dolibarr2203.request,dolibarr2203.bindings,await load()); const profile=buildProfile(dolibarr2203.request,normalized); const columns=profile.facts.map(({objectRef,columnRef})=>({objectRef,columnRef,disposition:['net_amount','tax_amount','gross_amount'].includes(columnRef)?'APPROVED_AGGREGATE':'REVIEW_REQUIRED'})); const review=reviewProfile(profile,{profileDigest:profile.profileDigest,scopeDigest:sha256(profile.scope),columns}); return {approved:approveProfile(profile,review),normalized}; };
test('MariaDB is the sole engine-specific adapter and emits the normalized contract',async()=>{ const plan=planMariaDbProfile(dolibarr2203.request,dolibarr2203.bindings); assert.equal(plan.length,10); assert.ok(plan.every((entry)=>/^SELECT COUNT\(\*\)/.test(entry.sql))); const {normalized}=await approve(); assert.equal(normalized.schemaVersion,'chimpmaera.bi/normalized-profile-observations/v1'); assert.equal(normalized.columns[0].objectRef,'orders'); assert.equal(normalized.columns[0].columnRef,'created_at'); });
test('Dolibarr knowledge and recomputation remain in fixture layer; Superset input is approved-profile-only',async()=>{ const {approved}=await approve(); const recomputation={orders:{recordCount:3,netAmount:600,taxAmount:114,grossAmount:714},invoices:{recordCount:2,netAmount:300,taxAmount:57,grossAmount:357}}; const knowledge=deriveDolibarrKnowledge(approved,recomputation); const projection=buildProjection(approved,dolibarrProjectionSpec(approved,recomputation)); const bundle=createSupersetBundle(approved,projection,{datasetName:'cm_discovery_s2_sales_profile',title:'Dolibarr orders and invoices'}); assert.equal(knowledge.approvalId,approved.approvalId); assert.deepEqual(projection.rows,[{recordType:'ORDER',...recomputation.orders},{recordType:'INVOICE',...recomputation.invoices}]); assert.equal(bundle.source.kind,'APPROVED_PROFILE_PROJECTION'); assert.equal(bundle.source.directSourceRoute,false); assert.ok(bundle.dashboard.charts.some((chart)=>chart.name.includes('drill-through'))); });
test('adapter-normalized input contains no MariaDB metadata shapes or Dolibarr identifiers',async()=>{ const {normalized}=await approve(); const serialized=JSON.stringify(normalized); assert.doesNotMatch(serialized,/llx_|dolidb|column_type|information_schema|SELECT /i); });
