import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { ADAPTER_CONTRACT, approveProfile, buildProfile, buildProjection, reviewProfile, sha256 } from '../scripts/lib/bi-discovery-s2/core.mjs';

const request={schemaVersion:'chimpmaera.bi/profile-request/v1',scope:{tenantId:'synthetic',sourceId:'source-a',scanId:'scan-a',sourceDigest:'digest-a'},selection:{rowSamples:false,objects:[{objectRef:'events',columns:['occurred_at','value','label']}]},budgets:{maxObjects:1,maxColumns:3,maxQueries:3,timeoutMs:100,maxDistributionBuckets:4,rowSamples:false}};
const normalized={schemaVersion:ADAPTER_CONTRACT,scope:request.scope,execution:{readOnly:true,cancelSafe:true,rowSamples:false,queryCount:3,elapsedMs:4},columns:[{objectRef:'events',columnRef:'occurred_at',evidenceRef:'e:1',typeFamily:'TEMPORAL',rowCount:4,nullCount:0,distinctCount:4,minimum:'2026-01-01',maximum:'2026-01-04',freshnessMaximum:'2026-01-04'},{objectRef:'events',columnRef:'value',evidenceRef:'e:2',typeFamily:'NUMERIC',rowCount:4,nullCount:1,distinctCount:3,minimum:1,maximum:9},{objectRef:'events',columnRef:'label',evidenceRef:'e:3',typeFamily:'TEXT',rowCount:4,nullCount:0,distinctCount:2,distribution:[{value:'a',count:3},{value:'b',count:1}]}]};

test('generic core consumes only adapter-normalized synthetic observations deterministically',()=>{ const first=buildProfile(request,normalized),second=buildProfile(request,structuredClone(normalized)); assert.deepEqual(first,second); assert.deepEqual(first.facts.map((x)=>x.candidate),['LOW_CARDINALITY_CANDIDATE','TEMPORAL_CANDIDATE','UNIQUE_VALUE_CANDIDATE']); });
test('immutable review and approval bind exact scope/profile and projection permits approved aggregates only',()=>{ const profile=buildProfile(request,normalized); const review=reviewProfile(profile,{profileDigest:profile.profileDigest,scopeDigest:sha256(profile.scope),columns:[{objectRef:'events',columnRef:'value',disposition:'APPROVED_AGGREGATE'},{objectRef:'events',columnRef:'label',disposition:'EXCLUDED_SENSITIVE'}]}); const approved=approveProfile(profile,review); assert.ok(approved.approvalId.startsWith('approved:sha256:')); assert.equal(buildProjection(approved,{approvalId:approved.approvalId,fields:[{objectRef:'events',columnRef:'value',aggregation:'SUM'}],rows:[{value:12}]}).rows[0].value,12); assert.throws(()=>buildProjection(approved,{approvalId:approved.approvalId,fields:[{objectRef:'events',columnRef:'label'}],rows:[]}),/PROFILE_SENSITIVE_PROJECTION_DENIED/); });
test('denials cover stale/foreign scope, excess selection, timeout, incomplete normalized input and row samples',()=>{ assert.throws(()=>buildProfile({...request,scope:{...request.scope,sourceDigest:'changed'}},normalized),/PROFILE_FOREIGN_SCOPE/); assert.throws(()=>buildProfile({...request,budgets:{...request.budgets,maxColumns:2}},normalized),/PROFILE_COLUMN_BUDGET_EXCEEDED/); assert.throws(()=>buildProfile(request,{...normalized,execution:{...normalized.execution,elapsedMs:101}}),/PROFILE_TIMEOUT/); assert.throws(()=>buildProfile(request,{...normalized,columns:normalized.columns.slice(1)}),/PROFILE_OBSERVATION_INCOMPLETE/); assert.throws(()=>buildProfile({...request,selection:{...request.selection,rowSamples:true}},normalized),/PROFILE_ROW_SAMPLES_DISABLED/); });
test('generic core has zero application identifiers, engine names, SQL, or engine metadata vocabulary',async()=>{ const source=await readFile(new URL('../scripts/lib/bi-discovery-s2/core.mjs',import.meta.url),'utf8'); assert.doesNotMatch(source,/Dolibarr|MariaDB|llx_|information_schema|SELECT\s|columnType|engineVersion/i); });
