import assert from "node:assert/strict";
import test from "node:test";
import { GOVERNED_WORKLOAD_REQUEST_SCHEMA_V1, type GovernedWorkloadRequestV1 } from "../packages/contracts/src/development-worker.js";
import { DevWorkerDenied, sha256 } from "../packages/dev-worker/src/controller.js";
import { GovernedWorkloadControllerV1, deterministicFixtureAdapter, type GovernancePolicyV1 } from "../packages/dev-worker/src/m3-governance.js";

const NOW = "2026-08-09T12:00:00.000Z", writerId = "workload:cm-dev-writer-m3", reviewerId = "workload:cm-dev-reviewer-m3";
const openCode = deterministicFixtureAdapter("opencode-contract-fixture", { fixture: "opencode-shape", network: false });
const portable = deterministicFixtureAdapter("portable-local-fixture", { fixture: "portable-json", network: false });
function policy(overrides: Partial<GovernancePolicyV1> = {}): GovernancePolicyV1 { return { enabled: true, global: { maxParallel: 3, maxRequests: 8, maxCostMicros: 100 }, projects: { "project:chimpmaera": { maxParallel: 2, maxRequests: 6, maxCostMicros: 80 } }, providers: { "provider:writer": { maxParallel: 2, maxRequests: 4, maxCostMicros: 60 }, "provider:reviewer": { maxParallel: 1, maxRequests: 4, maxCostMicros: 30 } }, adapters: [openCode, portable].map(({ id, version, configDigest }) => ({ id, version, configDigest })), writerIdentity: writerId, reviewerIdentity: reviewerId, ...overrides }; }
function request(adapter = openCode, workload: "WRITER" | "REVIEWER" = "WRITER", suffix = "a"): GovernedWorkloadRequestV1 { const reviewer = workload === "REVIEWER"; const unsigned = { schemaVersion: GOVERNED_WORKLOAD_REQUEST_SCHEMA_V1, requestId: `run:${workload.toLowerCase()}-${suffix}`, workload, workloadIdentity: reviewer ? reviewerId : writerId, projectId: "project:chimpmaera", issueIid: 117, workOrderId: "order:issue-117-m3", workOrderDigest: "1".repeat(64), lease: { id: `lease:${workload.toLowerCase()}-${suffix}`, kind: workload, expiresAt: "2026-08-09T12:05:00.000Z" }, adapter: { id: adapter.id, version: adapter.version, configDigest: adapter.configDigest }, provider: { id: reviewer ? "provider:reviewer" : "provider:writer", modelAlias: reviewer ? "cm.dev.review" as const : "cm.dev.fast" as const }, budget: { requests: 1, costMicros: reviewer ? 5 : 10 }, evidenceDigest: "2".repeat(64), requestedCapabilities: reviewer ? ["cm.dev.evidence.read" as const] : ["cm.dev.model.invoke" as const, "cm.dev.test.run" as const], expiresAt: "2026-08-09T12:05:00.000Z" }; return { ...unsigned, requestDigest: sha256(unsigned) }; }
function mutate(value: GovernedWorkloadRequestV1, change: (draft: any) => void): GovernedWorkloadRequestV1 { const draft: any = structuredClone(value); change(draft); delete draft.requestDigest; return { ...draft, requestDigest: sha256(draft) }; }
async function denied(code: string, action: () => Promise<unknown>): Promise<void> { await assert.rejects(action, (error: unknown) => error instanceof DevWorkerDenied && error.code === code, code); }
function deferred(): { promise: Promise<void>; resolve: () => void } { let resolve!: () => void; const promise = new Promise<void>(done => { resolve = done; }); return { promise, resolve }; }

test("DEV-WORKER-M3-1 governance core succeeds through both deterministic local fixture adapters", async () => { for (const adapter of [openCode, portable]) { const receipt = await new GovernedWorkloadControllerV1(policy()).execute(request(adapter, "WRITER", adapter.id), adapter, NOW); assert.equal(receipt.workload, "WRITER"); assert.match(receipt.result.patchDigest!, /^[a-f0-9]{64}$/); assert.deepEqual(receipt.authority, { workspaceMutation: false, publication: false, budgetWidening: false, routeWidening: false, writerLeaseShared: false }); } });

test("DEV-WORKER-M3-2 synchronous admission denies oversubscription and same-issue/order double writers", async () => { const gate = deferred(); const held = deterministicFixtureAdapter("portable-local-fixture", { fixture: "portable-json", network: false }, gate.promise); const controller = new GovernedWorkloadControllerV1(policy({ adapters: [held, openCode].map(({ id, version, configDigest }) => ({ id, version, configDigest })) })); const first = controller.execute(request(held, "WRITER", "held"), held, NOW); await denied("WRITER_SCOPE_CONFLICT_DENIED", () => controller.execute(request(openCode, "WRITER", "same-issue"), openCode, NOW)); const second = controller.execute(mutate(request(openCode, "WRITER", "other"), d => { d.issueIid = 118; d.workOrderId = "order:issue-118-m3"; }), openCode, NOW); await denied("GOVERNANCE_BUDGET_EXHAUSTED", () => controller.execute(mutate(request(openCode, "WRITER", "over"), d => { d.issueIid = 119; d.workOrderId = "order:issue-119-m3"; }), openCode, NOW)); gate.resolve(); await Promise.all([first, second]); const orderGate = deferred(); const orderAdapter = deterministicFixtureAdapter("portable-local-fixture", { order: true }, orderGate.promise); const orderController = new GovernedWorkloadControllerV1(policy({ adapters: [{ id: orderAdapter.id, version: orderAdapter.version, configDigest: orderAdapter.configDigest }] })); const orderFirst = orderController.execute(request(orderAdapter, "WRITER", "order-held"), orderAdapter, NOW); await denied("WRITER_SCOPE_CONFLICT_DENIED", () => orderController.execute(mutate(request(orderAdapter, "WRITER", "same-order"), d => { d.issueIid = 999; }), orderAdapter, NOW)); orderGate.resolve(); await orderFirst; });

test("DEV-WORKER-M3-3 cumulative global, project and provider budgets exhaust fail closed", async () => { for (const limits of [{ global: { maxParallel: 2, maxRequests: 1, maxCostMicros: 100 } }, { projects: { "project:chimpmaera": { maxParallel: 2, maxRequests: 1, maxCostMicros: 100 } } }, { providers: { "provider:writer": { maxParallel: 2, maxRequests: 1, maxCostMicros: 100 }, "provider:reviewer": { maxParallel: 1, maxRequests: 4, maxCostMicros: 30 } } }]) { const controller = new GovernedWorkloadControllerV1(policy(limits)); await controller.execute(request(openCode, "WRITER", "spent"), openCode, NOW); await denied("GOVERNANCE_BUDGET_EXHAUSTED", () => controller.execute(mutate(request(openCode, "WRITER", "denied"), d => { d.issueIid = 118; d.workOrderId = "order:other"; }), openCode, NOW)); } });

test("DEV-WORKER-M3-4 reviewer is independent and cannot mutate, publish, widen or share writer authority", async () => { const controller = new GovernedWorkloadControllerV1(policy()); const receipt = await controller.execute(request(portable, "REVIEWER", "clean"), portable, NOW); assert.equal(receipt.result.patchDigest, null); assert.equal(receipt.result.reviewOutcome, "PASS"); for (const authority of ["WORKSPACE_WRITE", "PUBLISH", "WIDEN_PATHS", "WIDEN_ROUTE", "WIDEN_BUDGET"]) { const attack = deterministicFixtureAdapter("portable-local-fixture", { attack: authority }, undefined, { attemptedAuthorities: [authority] }); await denied("REVIEWER_AUTHORITY_ATTEMPT_DENIED", () => new GovernedWorkloadControllerV1(policy({ adapters: [{ id: attack.id, version: attack.version, configDigest: attack.configDigest }] })).execute(request(attack, "REVIEWER", authority.toLowerCase()), attack, NOW)); } await denied("WRONG_WORKLOAD_LEASE_DENIED", () => controller.execute(mutate(request(portable, "REVIEWER", "writer-lease"), d => { d.lease.kind = "WRITER"; }), portable, NOW)); await denied("WORKLOAD_AUTHORITY_DENIED", () => controller.execute(mutate(request(portable, "REVIEWER", "writer-cap"), d => { d.requestedCapabilities = ["cm.dev.model.invoke"]; }), portable, NOW)); });

test("DEV-WORKER-M3-5 mismatch, tampering, stale, wrong-workload and replay paths deny", async () => { await denied("ADAPTER_BINDING_DENIED", () => new GovernedWorkloadControllerV1(policy()).execute(request(portable, "WRITER", "mismatch"), openCode, NOW)); const tampered = deterministicFixtureAdapter("portable-local-fixture", { fixture: "tampered" }); const originalRun = tampered.run.bind(tampered); tampered.run = async input => ({ ...(await originalRun(input)), outputDigest: "0".repeat(64) }); await denied("ADAPTER_OUTPUT_TAMPERING_DENIED", () => new GovernedWorkloadControllerV1(policy({ adapters: [{ id: tampered.id, version: tampered.version, configDigest: tampered.configDigest }] })).execute(request(tampered, "WRITER", "tampered"), tampered, NOW)); for (const [code, changed] of [["STALE_OR_EXPIRED_WORKLOAD_DENIED", (d: any) => { d.expiresAt = NOW; }], ["WRONG_WORKLOAD_IDENTITY_DENIED", (d: any) => { d.workloadIdentity = reviewerId; }], ["MODEL_ROUTE_DENIED", (d: any) => { d.provider.modelAlias = "cm.dev.review"; }]] as const) await denied(code, () => new GovernedWorkloadControllerV1(policy()).execute(mutate(request(openCode, "WRITER", code.toLowerCase()), changed), openCode, NOW)); const replayController = new GovernedWorkloadControllerV1(policy()), replay = request(openCode, "WRITER", "replay"); await replayController.execute(replay, openCode, NOW); await denied("CONCURRENT_OR_REPLAY_REQUEST_DENIED", () => replayController.execute(replay, openCode, NOW)); const malformed = { ...request(openCode, "WRITER", "unknown"), unknown: true } as unknown as GovernedWorkloadRequestV1; await denied("GOVERNED_REQUEST_SCHEMA_OR_DIGEST_DENIED", () => new GovernedWorkloadControllerV1(policy()).execute(malformed, openCode, NOW)); });
test("DEV-WORKER-M3-6 default-off and retained writer ownership deny later or shared-lease workloads", async () => {
  await denied("GOVERNANCE_DISABLED_DENIED", () => new GovernedWorkloadControllerV1(policy({ enabled: false })).execute(request(openCode, "WRITER", "disabled"), openCode, NOW));
  const controller = new GovernedWorkloadControllerV1(policy());
  const writer = request(openCode, "WRITER", "owner");
  await controller.execute(writer, openCode, NOW);
  await denied("WRITER_SCOPE_CONFLICT_DENIED", () => controller.execute(request(openCode, "WRITER", "later"), openCode, NOW));
  const shared = mutate(request(portable, "REVIEWER", "shared"), draft => { draft.lease.id = writer.lease.id; });
  await denied("REVIEWER_WRITER_LEASE_SHARE_DENIED", () => controller.execute(shared, portable, NOW));
});
test("DEV-WORKER-M3-7 adapter exceptions are sanitized and consume the fail-closed reservation", async () => {
  const failing = deterministicFixtureAdapter("portable-local-fixture", { failure: true });
  failing.run = async () => { throw new Error("raw adapter detail must not escape"); };
  const controller = new GovernedWorkloadControllerV1(policy({ adapters: [{ id: failing.id, version: failing.version, configDigest: failing.configDigest }] }));
  await denied("ADAPTER_EXECUTION_DENIED", () => controller.execute(request(failing, "WRITER", "failure"), failing, NOW));
  await denied("WRITER_SCOPE_CONFLICT_DENIED", () => controller.execute(request(failing, "WRITER", "after-failure"), failing, NOW));
});
