SELECT
  COUNT(1) AS "rowCount",
  COUNT(1) - COUNT({{COLUMN}}) AS "nullCount",
  COUNT(DISTINCT {{COLUMN}}) AS "distinctCount",
  TO_CHAR(CAST(MIN({{COLUMN}}) AS TIMESTAMP), 'YYYY-MM-DD"T"HH24:MI:SS.FF7', 'NLS_DATE_LANGUAGE=English') AS "minimum",
  TO_CHAR(CAST(MAX({{COLUMN}}) AS TIMESTAMP), 'YYYY-MM-DD"T"HH24:MI:SS.FF7', 'NLS_DATE_LANGUAGE=English') AS "maximum",
  TO_CHAR(CAST(MAX({{COLUMN}}) AS TIMESTAMP), 'YYYY-MM-DD"T"HH24:MI:SS.FF7', 'NLS_DATE_LANGUAGE=English') AS "freshnessMaximum"
FROM {{SCHEMA}}.{{RELATION}};
